/**
 * record-detail.tsx — Read-only view of a single row, every column shown.
 *
 * Opened by clicking a row. Unlike the edit form (which only surfaces editable
 * columns), this shows the complete record — primary keys, computed columns,
 * foreign keys resolved to their labels, and the database-managed audit fields
 * — each tagged with a small role chip so it's clear what the database owns
 * versus what a user can change.
 */

import {
  ClockIcon,
  KeyRoundIcon,
  LinkIcon,
  PencilIcon,
  SparklesIcon,
  Trash2Icon,
  XIcon,
} from 'lucide-react'

import { motion } from 'motion/react'

import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { ScrollArea } from '@/components/ui/scroll-area'
import { PANEL_TITLE_ID } from '@/components/record-form'
import type { FkLabelMap } from '@/hooks/queries'
import { listContainer, listItem } from '@/lib/animations'
import { fieldLabel, formatValue, NULL_DISPLAY } from '@/lib/format'
import { cn } from '@/lib/utils'
import type { ColumnMeta, Row, TableMeta, TablePermissions } from '@/types'

function FieldValue({
  column,
  row,
  fkLabels,
}: {
  column: ColumnMeta
  row: Row
  fkLabels: FkLabelMap
}) {
  const value = row[column.name]

  if (column.foreign_key) {
    if (value == null) return <span className="text-muted-foreground/50">{NULL_DISPLAY}</span>
    const label = fkLabels[column.name]?.get(String(value))
    return (
      <span className="inline-flex items-center gap-2">
        <span className="rounded-md bg-accent px-1.5 py-0.5 text-xs font-medium text-accent-foreground ring-1 ring-inset ring-accent-foreground/15">
          {label ?? String(value)}
        </span>
        {label && (
          <span className="text-xs text-muted-foreground tabular-nums">#{String(value)}</span>
        )}
      </span>
    )
  }

  if (column.field_type === 'boolean') {
    if (value == null) return <span className="text-muted-foreground/50">{NULL_DISPLAY}</span>
    return (
      <span className="inline-flex items-center gap-1.5 text-sm">
        <span
          className={cn('size-1.5 rounded-full', value ? 'bg-success' : 'bg-muted-foreground/40')}
        />
        {value ? 'Yes' : 'No'}
      </span>
    )
  }

  const formatted = formatValue(value, column)
  if (formatted == null) return <span className="text-muted-foreground/50">{NULL_DISPLAY}</span>
  return <span className="text-sm break-words whitespace-pre-wrap tabular-nums">{formatted}</span>
}

/** A tiny role chip (key / FK / computed / audit), with an accessible title. */
function RoleChip({ column }: { column: ColumnMeta }) {
  if (column.is_primary_key) {
    return (
      <Badge variant="outline" className="gap-1 font-normal" title="Primary key">
        <KeyRoundIcon className="size-3" />
        Key
      </Badge>
    )
  }
  if (column.foreign_key) {
    return (
      <Badge variant="outline" className="gap-1 font-normal" title={`References ${column.foreign_key.table}`}>
        <LinkIcon className="size-3" />
        {column.foreign_key.table}
      </Badge>
    )
  }
  if (column.is_audit) {
    return (
      <Badge variant="outline" className="gap-1 font-normal text-muted-foreground" title="Set automatically by the database">
        <ClockIcon className="size-3" />
        Audit
      </Badge>
    )
  }
  if (!column.editable) {
    return (
      <Badge variant="outline" className="gap-1 font-normal text-muted-foreground" title="Generated by the database">
        <SparklesIcon className="size-3" />
        Auto
      </Badge>
    )
  }
  return null
}

interface RecordDetailProps {
  meta: TableMeta
  row: Row
  fkLabels: FkLabelMap
  permissions: TablePermissions
  onEdit: () => void
  onDelete: () => void
  onClose: () => void
}

export function RecordDetail({
  meta,
  row,
  fkLabels,
  permissions,
  onEdit,
  onDelete,
  onClose,
}: RecordDetailProps) {
  const title =
    meta.display_column && row[meta.display_column] != null
      ? String(row[meta.display_column])
      : meta.primary_key.map((k) => row[k]).join(', ')

  return (
    <div className="flex h-full flex-col">
      {/* Header */}
      <div className="flex items-start justify-between gap-4 border-b px-5 py-4">
        <div className="min-w-0 space-y-0.5">
          <h2 id={PANEL_TITLE_ID} className="truncate font-heading text-base font-semibold">
            {title}
          </h2>
          <p className="text-sm text-muted-foreground">
            {meta.schema}.{meta.name}
          </p>
        </div>
        <Button type="button" variant="ghost" size="icon-sm" onClick={onClose} aria-label="Close">
          <XIcon />
        </Button>
      </div>

      {/* All fields */}
      <ScrollArea className="min-h-0 flex-1">
        <motion.dl className="@container divide-y" variants={listContainer} initial="hidden" animate="visible">
          {meta.columns.map((column) => (
            <motion.div
              key={column.name}
              variants={listItem}
              className="grid grid-cols-1 gap-1 px-5 py-3 transition-colors hover:bg-muted/40 @md:grid-cols-[minmax(0,11rem)_1fr] @md:gap-4"
            >
              <dt className="flex flex-wrap items-center gap-1.5 text-sm text-muted-foreground">
                <span className="font-medium text-foreground/80">{fieldLabel(column)}</span>
                <RoleChip column={column} />
              </dt>
              <dd className="min-w-0">
                <FieldValue column={column} row={row} fkLabels={fkLabels} />
              </dd>
            </motion.div>
          ))}
        </motion.dl>
      </ScrollArea>

      {/* Actions */}
      {(permissions.update || permissions.delete) && (
        <div className="flex items-center justify-end gap-2 border-t bg-muted/30 px-5 py-3">
          {permissions.delete && (
            <Button
              type="button"
              variant="ghost"
              className="mr-auto text-muted-foreground hover:text-destructive"
              onClick={onDelete}
            >
              <Trash2Icon />
              Delete
            </Button>
          )}
          {permissions.update && (
            <Button type="button" onClick={onEdit}>
              <PencilIcon />
              Edit record
            </Button>
          )}
        </div>
      )}
    </div>
  )
}
